export { default as Home } from './Website-Pages/Home';
export { default as Blog } from './Website-Pages/Blog';
export { default as About } from './Website-Pages/About';
export { default as Virus } from './Website-Pages/Virus';
export { default as Music } from './Website-Pages/Music';
export { default as Notes } from './Website-Pages/Notes';
export { default as HardwareHacking } from './Website-Pages/HardwareHacking';
export { default as Purt } from './Website-Pages/PURT';
export { default as NotFound } from './Website-Pages/NotFound';
